const queryKeys = {
    GET_BENEFICIARIES: "GET_BENEFICIARIES",
    GET_COUNTRIES: "GET_COUNTRIES",
    GET_BANK_BY_COUNTRY_CODE: "GET_BANK_BY_COUNTRY_CODE",
    GET_LOGGED_IN_USER_ACCOUNT: "GET_LOGGED_IN_USER_ACCOUNT",
    GET_USER_ACCOUNT_INFO: "GET_USER_ACCOUNT_INFO"
};

export default queryKeys;
